before_script:
  # This is mandatory for brigit to work
  - git config --global user.email "gitlab-runner@exemple.com"
  - git config --global user.name "Gitlab Runner"
  - git config --global advice.statusHints false

.test_template: &test
  script:
    - python setup.py test

python 2.7:
  image: python:2.7
  <<: *test

python 3.3:
  image: python:3.3
  <<: *test

python 3.4:
  image: python:3.4
  <<: *test

python 3.5:
  image: python:3.5
  <<: *test
